version: "3.7"
services:
  shellinabox:
    image: xanmarta/shellinadocker:podman
    privileged: true
    ports:
      - 8000:8000
    volumes:
      - shell_data:/data
    restart: unless-stopped

volumes:
  shell_data: {}
